### PR TITLE
update to swift 4

### PR DESCRIPTION
**Pull request by grifas**

### CODE REVIEW

**Review by Bashta — APPROVED** [review]
Please approve this PR!

**Comment by andre991** [comment]
Please merge this PR!

**Comment by grifas** [comment]
It seems this lib is abandoned :/

**Comment by StephanWalters** [comment]
MERGE THE PR!

**Comment by iamabhiee** [comment]
Merge please

**Comment by yhkaplan** [comment]
I made a maintained range slider if any of you are interested: https://github.com/yhkaplan/DoubleSlider

**Pull request closed without merging**
